workflows:
  # iOS Build Workflow (Development)
  ios-workflow:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.iatinleong.sparkconnect
      vars:
        # Supabase 環境變數（需要在 Codemagic 設定）
        VITE_SUPABASE_URL: $VITE_SUPABASE_URL
        VITE_SUPABASE_PUBLISHABLE_KEY: $VITE_SUPABASE_PUBLISHABLE_KEY
        VITE_SUPABASE_PROJECT_ID: $VITE_SUPABASE_PROJECT_ID
      node: latest
      xcode: 15.0.1
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Update Capacitor dependencies
        script: |
          npx cap sync ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - iatinleong@gmail.com
        notify:
          success: true
          failure: true

  # Android Build Workflow
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        VITE_SUPABASE_URL: $VITE_SUPABASE_URL
        VITE_SUPABASE_PUBLISHABLE_KEY: $VITE_SUPABASE_PUBLISHABLE_KEY
        VITE_SUPABASE_PROJECT_ID: $VITE_SUPABASE_PROJECT_ID
      android_signing:
        - keystore_reference
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Update Capacitor dependencies
        script: |
          npx cap sync android
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - iatinleong@gmail.com
      google_play:
        credentials: $GPLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
