// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase 環境變數缺失！');
  console.error('VITE_SUPABASE_URL:', SUPABASE_URL ? '✅ 已設定' : '❌ 未設定');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅ 已設定' : '❌ 未設定');
  console.error('\n請在 Vercel 設定環境變數：');
  console.error('Settings → Environment Variables → Add');

  // 在頁面上顯示錯誤
  document.body.innerHTML = `
    <div style="display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; font-family: system-ui;">
      <div style="max-width: 600px; padding: 30px; background: #fee; border: 2px solid #f00; border-radius: 10px;">
        <h1 style="color: #c00; margin: 0 0 20px 0;">⚠️ 環境變數未設定</h1>
        <p style="margin: 0 0 15px 0;">請在 Vercel 設定以下環境變數：</p>
        <ul style="margin: 0 0 15px 0; padding-left: 20px;">
          <li><code>VITE_SUPABASE_URL</code></li>
          <li><code>VITE_SUPABASE_PUBLISHABLE_KEY</code></li>
          <li><code>VITE_SUPABASE_PROJECT_ID</code></li>
        </ul>
        <p style="margin: 0;">設定後記得點擊 <strong>Redeploy</strong> 重新部署！</p>
      </div>
    </div>
  `;

  throw new Error(
    '缺少 Supabase 環境變數。請在 Vercel 設定環境變數後重新部署。'
  );
}

// Create safe storage for iOS compatibility
const createSafeStorage = () => {
  try {
    const testKey = '__storage_test__';
    localStorage.setItem(testKey, 'test');
    localStorage.removeItem(testKey);
    return localStorage;
  } catch (e) {
    // Fallback to in-memory storage for iOS private mode
    console.warn('localStorage not available, using in-memory storage');
    let inMemoryStorage: Record<string, string> = {};
    return {
      getItem: (key: string) => inMemoryStorage[key] || null,
      setItem: (key: string, value: string) => { inMemoryStorage[key] = value; },
      removeItem: (key: string) => { delete inMemoryStorage[key]; },
      clear: () => { inMemoryStorage = {}; },
      key: (index: number) => Object.keys(inMemoryStorage)[index] || null,
      get length() { return Object.keys(inMemoryStorage).length; }
    };
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage() as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});